version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.13

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
    - "/go/pkg/mod"

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: make check-style
      - *save_cache

  test:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: make test
      - *save_cache

  build:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: make build
      - run: |
        if [[ `git status <<parameters.path>> --porcelain` ]]; then
          echo "ERROR: uncommitted changes"
          git status --porcelain
          exit 1
        fi
      - *save_cache

workflows:
  version: 2
  ci:
    jobs:
      - lint
      - test
      - build
