version: 2.1

executors:
  default:
    docker:
      - image: circleci/golang:1.13

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
    - "/go/pkg/mod"

commands:
  check-uncommitted:
    description: Check for uncommitted changes.
    steps:
      - run: 
          name: Check for uncomitted changes using git porcelain command.
          command: |
            if [[ `git status --porcelain` ]]; then
              echo "ERROR: uncommitted changes"
              git status --porcelain
              exit 1
            fi

jobs:
  build:
    executor:
      name: default
    steps:
      - checkout
      - *restore_cache
      - run: make check-style
      - run: make test
      - run: make build
      - check-uncommitted
      - *save_cache

workflows:
  version: 2
  ci:
    jobs:
      - build:
