blank_issues_enabled: true
contact_links:
  - name: Community Plugins in the Plugin Marketplace 
    url: https://developers.mattermost.com/extend/plugins/community-plugin-marketplace/
    about: Please read this before submitting a plugin
