name: cd
on:
  push:
    branches:
      - master
      - production
      - CLD-5459 # TODO: Remove before merge

env:
  GO_VERSION: 1.19.6

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: ci/setup-go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: ci/build
        run: make build

      - name: ci/upload-artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: cd/checkout-repo
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: cd/setup-node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c #v3.6.0
        with:
          node-version: "12.x"

      - name: ci/download-artifact
        uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7 # v3.0.1
        with:
          path: dist

      - name: Install Serverless CLI and dependencies
        run: |
          sudo npm i -g serverless@"<2.0.0"
      - name: Deploy Function
        #TODO: Update branch name before merge
        run:  |
          if [ "${GITHUB_REF_NAME}" == "CLD-5459" ]; then
            export AWS_ACCESS_KEY_ID=$MM_MARKETPLACE_AWS_STAGING_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$MM_MARKETPLACE_AWS_STAGING_SECRET_ACCESS_KEY
            sudo -E serverless deploy function -f server --stage staging
          elif [ "${GITHUB_REF_NAME}" == "production" ]; then
            export AWS_ACCESS_KEY_ID=$MM_MARKETPLACE_AWS_PRODUCTION_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$MM_MARKETPLACE_AWS_PRODUCTION_SECRET_ACCESS_KEY
            sudo -E serverless deploy function -f server --stage production
          else
            echo "Unexpected branch ${GITHUB_REF_NAME}"
            exit 1
          fi
