name: ci
on:
  pull_request:
  push:
    branches:
      - master
      - production

env:
  GO_VERSION: 1.19.6
  GOLANGCI_LINT_VERSION: v1.49.0

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: ci/setup-go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: ci/install-golangci-lint
        run: |
          curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${{ env.GOLANGCI_LINT_VERSION }}

      - name: ci/go-tidy
        run: go mod tidy -v

      - name: ci/check-diff-on-gomod
        run: git --no-pager diff --exit-code go.mod go.sum || (echo "Please run \"go mod tidy\" and commit the changes in go.mod and go.sum." && exit 1)

      - name: ci/checking-code-style
        run: make check-style

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: ci/fetch-master
        run: git fetch origin master:master

      - name: ci/setup-go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: ci/test
        run: make test
